### ISSUE TITLE
Twig helper

### ISSUE THREAD

**Issue by Quovandius** [artgris/MediaBundle#12]
Hi,

When i have save entity. i can found it in Artgris manager.

But i didn't found how can i display picture with twig ? i have try to dump attributes, but i can just found path and alt.

Sorry for the inconvenience.

**Comment by Arkounay** [comment]
It's designed to work in html/web, so since you have the path you can simply call something like: `<img src="{{ asset(entity.image.path) }}">`.
If you're using [Gregwar/ImageBundle](https://github.com/Gregwar/ImageBundle) to crop or resize the images, you can use the `filePath` function like so for example: `<img src="{{ image(entity.image.filePath).zoomCrop(800, 400) }}"`

**Comment by Quovandius** [comment]
Ok sorry,

with a wrong configuration of file manager, i have only the filename in path.

Thx for your patience and your help =)
