### ISSUE TITLE
Retain file size and file type

### ISSUE THREAD

**Issue by birkof** [artgris/MediaBundle#25]
In addition to alt & path attributes, how about getting file size and file type from frontend via JavaScript and save them as well?

**Comment by Arkounay** [comment]
For the next major version, we actually plan to remove the `path` attribute so the file path will only be stored as a plain string instead of json.
Storing informations as json seemed handy at first but we realised there are drawbacks, as the `alt` attribute is rarely used (and would require a different behaviour altogether for multilingual sites for example) and having a json can make things complex for no benefits (null checking, easy DB manipulation, DBs that don't support json, etc)
So the idea for the next version is to store plain string and let users add their own custom columns that they can populate through listeners for example

**Comment by Arkounay** [comment]
It will create a new column like now, but instead of storing a json like that in the DB: 
```json
{"alt": null, "path": "/images/image.jpg"}
```
only `/images/image.jpg` will be saved.  

Special doctrine types like `media` and `media_collection` will be removed, only `string` will be needed
So for collections, since the doctrine type for one image field will now be `string` you'll be able to use doctrine's `simple_array` for example (or even  `array` or `json`), and it'll work pretty much the same as before as long as you specify the form type. If you need to store special additional fields such as alt, you'll need to make new entity/class that has an image and the extra fields, and either store it in a table like a regular entity or keep it as a json like before if you use doctrine's `json` type.
